INSERT INTO questions (question, module, is_answered) VALUES ('What is n-tier (or multi-tier) architecture?', 'JAVA', FALSE);
INSERT INTO questions (question, module, is_answered) VALUES ('What are microservices? Advantages and disadvantages?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Separation of Concerns?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a layered design and why is it important in enterprise applications?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Dependency Injection?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the DAO pattern? When and how to implement?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is SOA? When to use?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are unit test, integration test, system test, regression test, acceptance test? What is the major difference between these?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is code coverage? Why is it used? How you can measure?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does mocking mean? How would you do it "manually" (i. e. without using any fancy framework)?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a test case? What is an assertion? Give examples!', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is TDD? What are the benefits?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the unit testing best practices? (Eg. how many assertion should a test case contain?)', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is arrange/act/assert pattern?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is continuous integration? Why is CI important?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why are tests important in the CI workflow?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Name some software that help the CI workflow!', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Continuous Delivery?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Continuous Deployment?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is DevOps?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of software-lifecycle models do you know?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a UML diagram? What kind of diagram types do you know?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a UML class diagram? What are the typical elements?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of design patterns do you know? Bring at least 3 examples.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the purpose of the Iterator Pattern?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What do you know about the SOLID principles?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How would you separate data storage code and business logic code (which uses stored data) in an application?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between Stack and Queue data structure?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a graph? What are simple graphs? What are directed graphs? What are weighted graphs?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you store graphs in programs? What are the advantages/disadvantages per each?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are trees? What are binary trees? What are binary search trees?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are graph traversal algorithms? What is BFS, how does it work? What is DFS, how does it work?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How does dictionary work?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is it important for keys in a hashmap to have an immutable type? (Consider string for example.)', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is QuickSort? Describe the main logic of this sorting algorithm.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Basic Authentication?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is OAuth2?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is CORS, why it’s needed in browsers?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you initialize a CSRF attack?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is JWT used for? Where to store it on client side?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When do you need to use threads in an application?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a daemon thread?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between concurrent and parallel execution of code?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the most important problem developers are faced when using threads?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('In what kind of situations can deadlocks occur?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are possible ways to prevent deadlocks from occurring?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does critical section or critical region mean in the context of concurrent programming?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the possible uses of reflection?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Spring?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Spring Boot?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the major difference between the Standard edition (JSE) and Enterprise edition (JEE)? You can choose Spring (Spring Boot) instead of JavaEE. Focus on comparing them.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the advantages of the Spring Framework? Focus on the Core part.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a servlet? What is the purpose of DispatcherServlet in Spring?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When do you use RestControllers, when just simple Controllers?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Spring Application Context?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the main ways to define a bean in the Application Context?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Difference between .jar and .war files.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the major differences between Maven, Ant and Gradle?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Maven used for?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does a pom.xml file contains in Maven?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an ORM? What are the benefits, when to use?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between JDBC and JPA? Which are the advantages and disadvantages of each? Give a general overview.', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Hibernate? What are the advantages, limitations?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Name 3 different annotations used in JPA, what can they do for you?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is object-relational impedance mismatch?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a JpaRepository? What are the 2 main methods to define queries in them?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is the Set preferred over List when we want to store OneToMany relations?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of inheritance strategies are available? Which annotations are used to solve this?', 'JAVA', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Point out 5 suggestions, how to format an SQL query!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What layers can you name in a simple web application?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What error can occur, when an array does not have an element on the requested index?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why should we catch special exception types?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the "finally" block, and how would you use it?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is SQL injection? How to protect an application against it?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is XSS? How to protect an application against it?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to properly store passwords?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is HTTPS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is encryption and decryption?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is hashing?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between encryption and hashing? When would you use which?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What encryption methods do you know?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What hashing methods do you know?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How/where would you store sensitive data (like db password, API key, ...) of your application?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between Stack and Queue data structure?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is BubbleSort? Describe the main logic of this sorting algorithm.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain the process of finding the maximum and minimum value in a list of numbers!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain the process of calculating the average value in an array of numbers!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Big O complexity? Explain time and space complexity!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain the process of calculating the average value in a linked list of numbers!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How the CASE condition works in SQL?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How the switch-case condition works in JavaScript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to achieve a switch-case-like structure in Python?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain variable scoping in Python!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What’s the difference between const and var in JavaScript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How the list comprehension looks like in Python?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How the ternary expression looks like in JavaScript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How the ternary expression looks like in Python?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to import a function from another module in Python?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to import a function from another module in JavaScript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is recursion?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Write a recursive function which calculates the Fibonacci numbers!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to store a function in a variable in Python?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('List the ways of defining a callable logical unit in JavaScript!', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an event listener? How to attach one?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to trigger an event in JavaScript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a Python decorator? How does it work? Tell some examples of its usage.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a callback function? Tell some examples of its usage.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between synchronous and asynchronous execution?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you connect your application to a database server? What are the possible ways?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When do you use the DISTINCT keyword in SQL?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are aggregate functions in SQL? Give 3 examples.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of JOIN types do you know in SQL? Could you give examples?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the constraints in sql?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a cursor in SQL? Why would you use one?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are database indexes? When to use?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are database transactions? When to use?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of database relations do you know? How to define them?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('You have a table with an “address” field which contains data like: 3525, Miskolc, Régiposta 9. (postcode, city, street name and address). How would you query all records related to Miskolc?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How would you keep track of what kind of data has changed after an UPDATE or DELETE operation in a table?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What’s the difference between XML, XHTML and HTML?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to include a JavaScript file in a webpage?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to include a CSS file in a webpage?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to select an element using its id in CSS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to select elements using their class in CSS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to select elements which have the ‘alpha’ and ‘beta’ classes in CSS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to select all list items in all ordered lists on the page in CSS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to select elements using their attributes in CSS?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are UX and UI?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Please list some points that an application should fulfill to have good UX.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is XML, XSLT, DTD?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between HTML and XML?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is javascript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When to use AJAX? Bring examples of its usage.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is DOM and how to manipulate it from Javascript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are events and how/why to use them in Javascript?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is event bubbling/capturing? How would you use it?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is JSON and how do we use it?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What type of branching strategy would you use?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What would you do if you find a bug on the production code (master branch)?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you move changes from one branch to another in GIT?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How does a VCS help with code reviews?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is your favorite git command? Why?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does remote/local mean in Git?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is it good to use a package manager software?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is it good to use a virtual environment for a project?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of HTTP status codes do you know?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is REST API?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a API?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is JSON? When to use?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is TCP/IP? What layers does it define, what are they responsible for?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What’s the difference between TCP and UDP?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How does an HTTP Request look like? What are the most relevant HTTP header fields?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How does an HTTP Response look like? What are the most relevant HTTP header fields?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is DNS? How does it work?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain the client-server architecture.', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a web server?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What would you use a session for?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What would you use a cookie for?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of software development methodologies do you know? What are the main features of these?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the SCRUM roles?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the SCRUM ceremonies?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the SCRUM artifacts?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the main goal of a retrospective meeting?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain, when would you recommend to use the waterfall methodology?', 'WEB', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the purpose of a list (array in some programming languages) data structure? Name some methods of it!', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between a list/array and a set?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the purpose and methods of a dictionary/map data structure?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Fibonacci sequences. Write a method (or pseudo code), that generates the Fibonacci sequences.', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you find a max value in a list/array if you can’t use any built-in functions?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you find the average of values in a list/array if you can’t use any built-in functions?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What do we call an *in-place* sort?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain an algorithm which sorts a list!', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the call stack?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is “Stack overflow”?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the main parts of a function?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you use a dictionary in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does it mean that an object is immutable in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is conditional expression in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are different types of arguments in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is variable shadowing? (context: variable scope)', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What can happen if you try to delete/drop/add an item from a List, while you are iterating over it in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the golden rule of variable scoping in Python (context: LEGB)? What is the lifetime of variables?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('If you need to access the iterator variable after a "for loop" how would you do it in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What type of elements can a list contain in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is slice operator in Python and how to use?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What arithmetic operators (+,*,-,/) can be used on lists in Python? What do they do?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the purpose of the in and not in membership operators in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does the + operator mean when used with strings in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Name 4 iterable types in Python!', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain f strings in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between list/set/dictionary comprehension and a generator expression in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Does the order of the function definitions matter in Python? Why?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What happens when you try to assign the result of a function which has no return statement to a variable in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does unpacking mean in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What techniques can you use while debugging a program in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does step over, step into and step out mean while using the debugger?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you start to debug a program from a certain line using the debugger?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the advantages of using a version control system?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between the working directory, the staging area and the repository in git?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are remote repositories in git?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why does a merge conflict occur?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Through what series of commands could you put a new file into a remote repository connected to your existing local repository?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does it mean atomic commits and descriptive commit messages?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What’s the difference between git and GitHub?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does clean code mean?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What steps do we usually do during a clean code refactoring?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is exception handling?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the basics of exception handling in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('In which case should we catch an exception? Why?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What can/should we do with an exception in the ‘except’ block?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does the else and finally statement do in a try-except block in Python?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the main goal of a retrospective meeting?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is UNIX and what is Linux?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What do we call the shell in Linux?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does root means in a Linux environment?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you access your personal files in Linux?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you install an application in Linux?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is package management in Linux, what are repositories?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you navigate in the filesystem with the command line?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does the following commands do: mkdir, rm, cat, cp, touch?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you look up what does a command do in Linux if you have no internet connection?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does the following commands do: head, tail, more, less?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you download a file from internet using the terminal?', 'PROGBASICS', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does "fail fast" mean in terms of exception handling? Why is it a good practice?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How to find the middle element of singly linked list in O(n)?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a linked list? How to find if a linked list has a loop?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the Big O time complexity of the common operations in an ArrayList, LinkedList, HashMap? And of a bubble sort, quicksort, finding items in a Binary Search tree?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How does HashMap work?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is it important for keys in a map to have an immutable type? (Consider String for example.)', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a garbage collector, in a nutshell?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is casting? What is the difference between up vs downcasting?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Which order should we catch the exceptions? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an object?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is a constructor?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Do we require parameter for constructors?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an interface?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are access modifiers?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is data hiding?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Can a static method use non-static members?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between hiding a static method and overriding an instance method?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Define the following terms: Instantiation, Attribute, Method.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Could we access a static variable (or method) from a non-static method? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Could we access a non-static variable (or method) from a static method? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How many instances you have of a static variable of a given class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is it not a good practice to write a lot of static methods?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the features of static attributes and static methods of a class? What are the benefits, when to use them?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the ‘this’ reference?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are base class, subclass and superclass?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Draw an object oriented family (as entities, with relations) on the whiteboard.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Difference between overloading and overriding?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the Object Oriented Principles? Explain the concepts with realistic examples!', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is method overloading?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is method overriding?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain how object oriented languages attempt to simplify memory management for Programmers.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Explain the "Single Responsibility" principle!', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an object oriented program? Explain, show.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you make a class immutable? What do you need to watch out for?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How many instances can be created for an abstract class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is autoboxing and unboxing?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('If you have a variable, that shall store a positive whole number between 0 and 200, what primitive type would you use to store it?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the golden rule of variable scoping in Java? What is the lifetime of variables?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the purpose of the ‘equals()’ method?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between "==" and "equals()"?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does the ‘static’ keyword mean?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Why is the main() method declared as static? Explain.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the default access modifier in a class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the JVM?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between the JRE and the JDK?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between long and Long?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Can a long store bigger numbers than a Long?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What kind of packages do you know under java.util.* ? Bring at least 3 examples.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are the access modifiers in Java? Which one could we use for class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Can an “enum” contain methods in Java? Explain.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When would you use a private/protected/public attribute? What is the difference?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you prevent developers from subclassing a class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you prevent developers from overriding a method in a subclass?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How do you prevent developers from changing the value of a variable?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Think about money ;) How would you store a currency value, that shall support decimal parts? Think it through again, and try to think outside of the box!', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What happens if you try to call something, that you have no access to, because of data hiding?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What happens if you try to delete/drop an item from an array, while you are iterating over it?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What happens if you try to delete/drop/add an item from a List, while you are iterating over it?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What happens if you try to add an item to the end of an array, while you are iterating over it?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('If you need to access the iterator variable after a "for loop", how would you do it?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Which interfaces extend the Collection interface in Java. Which classes?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the connection between equals() and hashCode()? How are they used in HashMap?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the difference between checked exceptions and unchecked exceptions? Could you bring example for each?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is Error in Java and how does it relate to Exception?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When does "finally" block run? What it is used for? Could you give an example from your projects when you would use "finally"?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the largest number you can work with in Java?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When you use method overriding, can you change the access level of the method, from protected to public? Why?When you use method overriding, can you change the access level of the method, from public to protected? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Can the main method be overridden? Explain your answer!', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When you use method overriding, can you throw fewer exceptions in the subclass than in the parent class? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('When you use method overriding, can you throw more exceptions in the subclass than in the parent class? Why?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What does final mean in case of a variable, method or a class?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the super keyword?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What are “generics”? When to use? Show examples.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is the benefit of having “generic” containers?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('Given two Java programs on two different machines. How can you communicate between the two? What are the possible ways?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What is an annotation? What can be annotated and how? Show examples.', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('How can you connect your application to a database server? What are the possible ways?', 'OOP', false);
INSERT INTO questions (question, module, is_answered) VALUES ('What do you know about database normalization?', 'OOP', false);